<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Facebook\Module'                   => __DIR__ . '/Module.php',
    'Facebook\Controller\Facebook' 		=> __DIR__ . '/src/Facebook/Controller/Facebook.php',
	'Facebook\Controller\BaseFacebook' 	=> __DIR__ . '/src/Facebook/Controller/BaseFacebook.php',
);
